
import { Country } from './types';

export const COUNTRIES: Country[] = [
  // --- CENTRAL EUROPE ---
  { id: 'pl', name: 'Poland', flag: 'pl', region: 'CENTRAL_EUROPE', mascot: 'European Bison', sport: 'Speedway', cuisine: 'Bigos', dress: 'Kontusz', landmark: 'Wawel Royal Castle', symbol: 'Red Poppy', history: 'Solidarity Movement', funFact: 'The European Bison, Europe’s heaviest land animal, was brought back from extinction in Poland.', difficulty: 'MEDIUM' },
  { id: 'hu', name: 'Hungary', flag: 'hu', region: 'CENTRAL_EUROPE', mascot: 'Turul', sport: 'Water Polo', cuisine: 'Pörkölt', dress: 'Matyó Embroidery', landmark: 'Parliament Building', symbol: 'Tulip', history: 'Austro-Hungarian Empire', funFact: 'Hungary has won the most Olympic gold medals in Water Polo history.', difficulty: 'MEDIUM' },
  { id: 'cz', name: 'Czech Republic', flag: 'cz', region: 'CENTRAL_EUROPE', mascot: 'Double-tailed Lion', sport: 'Ice Hockey', cuisine: 'Svíčková', dress: 'Kroje', landmark: 'Charles Bridge', symbol: 'Rose', history: 'Velvet Revolution', funFact: 'The Czech Republic has the highest beer consumption per capita in the world.', difficulty: 'MEDIUM' },
  { id: 'sk', name: 'Slovakia', flag: 'sk', region: 'CENTRAL_EUROPE', mascot: 'Tatra Chamois', sport: 'Ice Hockey', cuisine: 'Bryndzové halušky', dress: 'Kroj', landmark: 'Bratislava Castle', symbol: 'Linden Tree', history: 'Great Moravia', funFact: 'Slovakia has the world’s highest number of castles and chateaux per capita.', difficulty: 'HARD' },
  { id: 'at', name: 'Austria', flag: 'at', region: 'CENTRAL_EUROPE', mascot: 'Golden Eagle', sport: 'Alpine Skiing', cuisine: 'Wiener Schnitzel', dress: 'Dirndl & Lederhosen', landmark: 'Schönbrunn Palace', symbol: 'Edelweiss', history: 'Habsburg Monarchy', funFact: 'The sewing machine was invented by an Austrian, Josef Madersperger.', difficulty: 'EASY' },

  // --- WESTERN EUROPE ---
  { id: 'gb', name: 'United Kingdom', flag: 'gb', region: 'WESTERN_EUROPE', mascot: 'Lion', sport: 'Cricket', cuisine: 'Roast Beef', dress: 'Tartan Kilt', landmark: 'Big Ben', symbol: 'Tudor Rose', history: 'Industrial Revolution', funFact: 'The UK is the only country in the world where you don’t need to put the country name on your postage stamps.', difficulty: 'EASY' },
  { id: 'fr', name: 'France', flag: 'fr', region: 'WESTERN_EUROPE', mascot: 'Gallic Rooster', sport: 'Football', cuisine: 'Coq au Vin', dress: 'Breton Shirt', landmark: 'Eiffel Tower', symbol: 'Fleur-de-lis', history: 'French Revolution', funFact: 'France is the most visited country in the world, receiving over 89 million tourists annually.', difficulty: 'EASY' },
  { id: 'de', name: 'Germany', flag: 'de', region: 'WESTERN_EUROPE', mascot: 'Federal Eagle', sport: 'Football', cuisine: 'Sauerbraten', dress: 'Dirndl', landmark: 'Brandenburg Gate', symbol: 'Cornflower', history: 'Reunification', funFact: 'Germany has over 1,500 different types of sausages and 300 types of bread.', difficulty: 'EASY' },
  { id: 'it', name: 'Italy', flag: 'it', region: 'WESTERN_EUROPE', mascot: 'Italian Wolf', sport: 'Cycling', cuisine: 'Pasta Carbonara', dress: 'Sartorial Suits', landmark: 'Colosseum', symbol: 'Lily', history: 'Renaissance', funFact: 'Italy has more UNESCO World Heritage sites than any other country in the world.', difficulty: 'EASY' },
  { id: 'es', name: 'Spain', flag: 'es', region: 'WESTERN_EUROPE', mascot: 'Bull', sport: 'Football', cuisine: 'Paella', dress: 'Flamenco Dress', landmark: 'Sagrada Família', symbol: 'Red Carnation', history: 'Golden Age', funFact: 'Spain produces nearly half of the world’s olive oil.', difficulty: 'EASY' },

  // --- NORTH AMERICA ---
  { id: 'us', name: 'United States', flag: 'us', region: 'NORTH_AMERICA', mascot: 'Bald Eagle', sport: 'Baseball', cuisine: 'Apple Pie', dress: 'Denim Jeans', landmark: 'Statue of Liberty', symbol: 'Rose', history: 'American Revolution', funFact: 'The US has the world’s largest economy and invented the internet (ARPANET).', difficulty: 'EASY' },
  { id: 'ca', name: 'Canada', flag: 'ca', region: 'NORTH_AMERICA', mascot: 'Beaver', sport: 'Ice Hockey', cuisine: 'Poutine', dress: 'Mountie Uniform', landmark: 'CN Tower', symbol: 'Maple Leaf', history: 'Confederation', funFact: 'Canada has the longest coastline of any country in the world, stretching over 202,000 kilometers.', difficulty: 'EASY' },
  { id: 'mx', name: 'Mexico', flag: 'mx', region: 'NORTH_AMERICA', mascot: 'Golden Eagle', sport: 'Charrería', cuisine: 'Mole Poblano', dress: 'Huipil', landmark: 'Chichen Itza', symbol: 'Dahlia', history: 'Aztec Empire', funFact: 'Mexico City is built on the ruins of the Aztec capital, Tenochtitlán, and is slowly sinking.', difficulty: 'MEDIUM' },

  // --- CARIBBEAN ---
  { id: 'jm', name: 'Jamaica', flag: 'jm', region: 'CARIBBEAN', mascot: 'Doctor Bird', sport: 'Cricket', cuisine: 'Ackee and Saltfish', dress: 'Bush Jacket', landmark: 'Blue Mountains', symbol: 'Lignum Vitae', history: 'Maroon Resistance', funFact: 'Jamaica has more churches per square mile than any other country in the world.', difficulty: 'MEDIUM' },
  { id: 'bs', name: 'Bahamas', flag: 'bs', region: 'CARIBBEAN', mascot: 'Flamingo', sport: 'Sloop Sailing', cuisine: 'Conch Salad', dress: 'Androsia', landmark: 'Queen\'s Staircase', symbol: 'Yellow Elder', history: 'Pirate Era', funFact: 'The Bahamas is home to the deepest blue hole in the world, Dean’s Blue Hole.', difficulty: 'HARD' },

  // --- OCEANIA ---
  { id: 'au', name: 'Australia', flag: 'au', region: 'OCEANIA', mascot: 'Kangaroo', sport: 'Cricket', cuisine: 'Meat Pie', dress: 'Akubra Hat', landmark: 'Sydney Opera House', symbol: 'Golden Wattle', history: 'Anzac Day', funFact: 'Australia is the only continent occupied by a single nation and is home to 21 of the 25 most venomous snakes.', difficulty: 'EASY' },
  { id: 'nz', name: 'New Zealand', flag: 'nz', region: 'OCEANIA', mascot: 'Kiwi', sport: 'Rugby Union', cuisine: 'Hāngī', dress: 'Kākahu (Cloak)', landmark: 'Milford Sound', symbol: 'Silver Fern', history: 'Treaty of Waitangi', funFact: 'New Zealand was the first country to give women the right to vote, in 1893.', difficulty: 'MEDIUM' },

  // --- SOUTH ASIA ---
  { id: 'in', name: 'India', flag: 'in', region: 'SOUTH_ASIA', mascot: 'Royal Bengal Tiger', sport: 'Field Hockey', cuisine: 'Biryani', dress: 'Sari', landmark: 'Taj Mahal', symbol: 'Lotus', history: 'Independence Movement', funFact: 'India is the world\'s largest democracy and the birthplace of four major world religions: Hinduism, Buddhism, Jainism, and Sikhism.', difficulty: 'EASY' },

  // --- EASTERN EUROPE & BALKANS ---
  { id: 'ro', name: 'Romania', flag: 'ro', region: 'EASTERN_EUROPE', mascot: 'Lynx', sport: 'Oina', cuisine: 'Mămăligă', dress: 'Ie (Blouse)', landmark: 'Bran Castle', symbol: 'Dog Rose', history: 'Dacian Kingdom', funFact: 'Oina is a traditional Romanian sport similar to baseball, dating back to the 14th century.', difficulty: 'HARD' },
  { id: 'bg', name: 'Bulgaria', flag: 'bg', region: 'EASTERN_EUROPE', mascot: 'Lion', sport: 'Volleyball', cuisine: 'Banitsa', dress: 'Nosia', landmark: 'Rila Monastery', symbol: 'Rosa Damascena', history: 'First Bulgarian Empire', funFact: 'Bulgaria is the only country in Europe that hasn’t changed its name since it was first established in 681 AD.', difficulty: 'MEDIUM' },
  { id: 'ua', name: 'Ukraine', flag: 'ua', region: 'EASTERN_EUROPE', mascot: 'Nightingale', sport: 'Sambo', cuisine: 'Borscht', dress: 'Vyshyvanka', landmark: 'Saint Sophia Cathedral', symbol: 'Sunflower', history: 'Kyiv Rus', funFact: 'Ukraine is home to the world’s deepest metro station, Arsenalna, at 105.5 meters deep.', difficulty: 'MEDIUM' },
  { id: 'rs', name: 'Serbia', flag: 'rs', region: 'EASTERN_EUROPE', mascot: 'White Eagle', sport: 'Water Polo', cuisine: 'Sarma', dress: 'Šajkača', landmark: 'Belgrade Fortress', symbol: 'Plum', history: 'Nemanjić Dynasty', funFact: 'Serbia produces about 30% of the world’s raspberries.', difficulty: 'HARD' },
  { id: 'hr', name: 'Croatia', flag: 'hr', region: 'EASTERN_EUROPE', mascot: 'Marten (Kuna)', sport: 'Water Polo', cuisine: 'Crni rižot', dress: 'Šestine costume', landmark: 'Dubrovnik Old Town', symbol: 'Iris', history: 'Republic of Ragusa', funFact: 'The necktie (cravat) originated from 17th-century Croatian mercenaries.', difficulty: 'MEDIUM' },

  // --- AFRICA ---
  { id: 'dz', name: 'Algeria', flag: 'dz', region: 'AFRICA', mascot: 'Fennec Fox', sport: 'Football', cuisine: 'Couscous', dress: 'Karakou', landmark: 'Notre Dame d\'Afrique', symbol: 'Desert Rose', history: 'Berber Resistance', funFact: 'Algeria is the largest country in Africa by land area, almost 80% of which is the Sahara Desert.', difficulty: 'MEDIUM' },
  { id: 'cm', name: 'Cameroon', flag: 'cm', region: 'AFRICA', mascot: 'Indomitable Lion', sport: 'Football', cuisine: 'Ndolé', dress: 'Toghu', landmark: 'Mount Cameroon', symbol: 'Lobea', history: 'Bamum Kingdom', funFact: 'Cameroon is often called "Africa in miniature" because it exhibits all the major climates and vegetation of the continent.', difficulty: 'MEDIUM' },
  { id: 'ci', name: 'Ivory Coast', flag: 'ci', region: 'AFRICA', mascot: 'Elephant', sport: 'Football', cuisine: 'Garba', dress: 'Pagne', landmark: 'Basilica of Our Lady of Peace', symbol: 'Palm Tree', history: 'Akan Migration', funFact: 'The Ivory Coast is the world’s leading producer and exporter of cocoa beans.', difficulty: 'MEDIUM' },
  { id: 'na', name: 'Namibia', flag: 'na', region: 'AFRICA', mascot: 'Oryx', sport: 'Rugby', cuisine: 'Kapana', dress: 'Odelela', landmark: 'Sossusvlei Dunes', symbol: 'Welwitschia', history: 'Nama-Herero Resistance', funFact: 'Namibia is home to the highest sand dunes in the world in the Namib Desert.', difficulty: 'HARD' },
  { id: 'ml', name: 'Mali', flag: 'ml', region: 'AFRICA', mascot: 'Hippo', sport: 'Football', cuisine: 'Tigadegena', dress: 'Bogolanfini', landmark: 'Djinguereber Mosque', symbol: 'Hibiscus', history: 'Mali Empire of Mansa Musa', funFact: 'The Great Mosque of Djenné in Mali is the largest mud-brick building in the world.', difficulty: 'HARD' },
  { id: 'ug', name: 'Uganda', flag: 'ug', region: 'AFRICA', mascot: 'Grey Crowned Crane', sport: 'Football', cuisine: 'Matooke', dress: 'Gomesi', landmark: 'Murchison Falls', symbol: 'Cotton Flower', history: 'Buganda Kingdom', funFact: 'Uganda is one of only three countries where you can see mountain gorillas in the wild.', difficulty: 'MEDIUM' },
  { id: 'zw', name: 'Zimbabwe', flag: 'zw', region: 'AFRICA', mascot: 'Sable Antelope', sport: 'Cricket', cuisine: 'Sadza', dress: 'Reticulated Pattern', landmark: 'Great Zimbabwe Ruins', symbol: 'Flame Lily', history: 'Munhumutapa Empire', funFact: 'The Great Zimbabwe ruins are the largest ancient structure in sub-Saharan Africa.', difficulty: 'HARD' },
  { id: 'bj', name: 'Benin', flag: 'bj', region: 'AFRICA', mascot: 'Leopard', sport: 'Football', cuisine: 'Amoo', dress: 'Gelede', landmark: 'The Door of No Return', symbol: 'Rosewood', history: 'Kingdom of Dahomey', funFact: 'Benin is considered the birthplace of Vodun (Voodoo), which is an official religion in the country.', difficulty: 'HARD' },
  { id: 'tn', name: 'Tunisia', flag: 'tn', region: 'AFRICA', mascot: 'Eagle of Carthage', sport: 'Handball', cuisine: 'Lablabi', dress: 'Jebba', landmark: 'El Jem Amphitheatre', symbol: 'Jasmine', history: 'Carthaginian Empire', funFact: 'Tunisia’s city of Kairouan is the fourth holiest city in the Islamic world.', difficulty: 'MEDIUM' },
  { id: 'zm', name: 'Zambia', flag: 'zm', region: 'AFRICA', mascot: 'African Fish Eagle', sport: 'Football', cuisine: 'Nshima', dress: 'Musisi', landmark: 'Victoria Falls', symbol: 'Bougainvillea', history: 'Lunda Empire', funFact: 'Victoria Falls, located on the border of Zambia and Zimbabwe, is one of the world’s largest waterfalls.', difficulty: 'MEDIUM' },
  { id: 'ng', name: 'Nigeria', flag: 'ng', region: 'AFRICA', mascot: 'Eagle', sport: 'Dambe (Boxing)', cuisine: 'Jollof Rice', dress: 'Agbada', landmark: 'Zuma Rock', symbol: 'Yellow Trumpet', history: 'Benin Empire', funFact: 'Nigeria is home to Nollywood, the second-largest film industry in the world by volume.', difficulty: 'EASY' },
  { id: 'sn', name: 'Senegal', flag: 'sn', region: 'AFRICA', mascot: 'Lion', sport: 'Laamb (Wrestling)', cuisine: 'Thieboudienne', dress: 'Grand Boubou', landmark: 'African Renaissance Monument', symbol: 'Baobab', history: 'Jolof Empire', funFact: 'Laamb is a form of folk wrestling that allows both physical strikes and grappling.', difficulty: 'HARD' },
  { id: 'ke', name: 'Kenya', flag: 'ke', region: 'AFRICA', mascot: 'Lion', sport: 'Long-distance Running', cuisine: 'Ugali', dress: 'Maasai Shuka', landmark: 'Maasai Mara', symbol: 'Orchid', history: 'Mau Mau Uprising', funFact: 'Kenya is world-renowned for its distance runners who train at high altitudes in Iten.', difficulty: 'EASY' },
  { id: 'za', name: 'South Africa', flag: 'za', region: 'AFRICA', mascot: 'Springbok', sport: 'Rugby', cuisine: 'Bobotie', dress: 'Madiba Shirt', landmark: 'Table Mountain', symbol: 'King Protea', history: 'Apartheid Resistance', funFact: 'South Africa is the only country in the world to have hosted the FIFA, Rugby, and Cricket World Cups.', difficulty: 'EASY' },
  { id: 'eg', name: 'Egypt', flag: 'eg', region: 'AFRICA', mascot: 'Steppe Eagle', sport: 'Squash', cuisine: 'Kushari', dress: 'Galabeya', landmark: 'Great Sphinx of Giza', symbol: 'Lotus', history: 'Pharaonic Era', funFact: 'Egypt is a global powerhouse in professional Squash, often occupying most of the top 10 world rankings.', difficulty: 'MEDIUM' },
  { id: 'et', name: 'Ethiopia', flag: 'et', region: 'AFRICA', mascot: 'Walia Ibex', sport: 'Genna', cuisine: 'Kitfo', dress: 'Netela', landmark: 'Rock-Hewn Churches of Lalibela', symbol: 'Meskel Daisy', history: 'Kingdom of Aksum', funFact: 'Ethiopia is the only African nation never to have been formally colonized.', difficulty: 'HARD' },

  // --- ASIA ---
  { id: 'jp', name: 'Japan', flag: 'jp', region: 'ASIA', mascot: 'Green Pheasant', sport: 'Kyūdō', cuisine: 'Takoyaki', dress: 'Yukata', landmark: 'Mount Fuji', symbol: 'Cherry Blossom', history: 'Edo Period', funFact: 'Kyūdō is the traditional Japanese art of archery, emphasizing spiritual growth.', difficulty: 'MEDIUM' },
  { id: 'vn', name: 'Vietnam', flag: 'vn', region: 'ASIA', mascot: 'Water Buffalo', sport: 'Vovinam', cuisine: 'Bún Chả', dress: 'Áo Dài', landmark: 'Ha Long Bay', symbol: 'Lotus', history: 'Nguyễn Dynasty', funFact: 'Bún Chả gained global fame when President Obama enjoyed it in Hanoi.', difficulty: 'MEDIUM' },
  { id: 'bt', name: 'Bhutan', flag: 'bt', region: 'ASIA', mascot: 'Takin', sport: 'Archery', cuisine: 'Ema Datshi', dress: 'Gho', landmark: 'Tiger\'s Nest Monastery', symbol: 'Blue Poppy', history: 'Wangchuck Dynasty', funFact: 'Bhutan is the only country in the world that measures GNH—Gross National Happiness.', difficulty: 'HARD' },

  // --- LATIN AMERICA ---
  { id: 'pe', name: 'Peru', flag: 'pe', region: 'LATIN_AMERICA', mascot: 'Vicuña', sport: 'Paleta Frontón', cuisine: 'Lomo Saltado', dress: 'Chullo', landmark: 'Machu Picchu', symbol: 'Cantuta', history: 'Inca Empire', funFact: 'Peru grows over 3,000 different varieties of potatoes.', difficulty: 'MEDIUM' },
  { id: 'co', name: 'Colombia', flag: 'co', region: 'LATIN_AMERICA', mascot: 'Andean Condor', sport: 'Tejo', cuisine: 'Ajiaco', dress: 'Vueltiao', landmark: 'Salt Cathedral of Zipaquirá', symbol: 'Orchid', history: 'Bolívar Liberation', funFact: 'Tejo involves throwing metal discs at targets containing small gunpowder charges.', difficulty: 'HARD' }
];

export const CATEGORIES_ORDER: string[] = ['FLAG', 'MASCOT', 'SPORT', 'CUISINE', 'DRESS', 'LANDMARK', 'SYMBOL', 'HISTORY'];
